### ISSUE TITLE
Does not seem to run tslint

### ISSUE THREAD

**Issue by rzymek** [TouK/sputnik#165] opened 2017-05-30 12:12 UTC
Whatever I do, I'm always getting:
>  Adding static passing score {Code-Review=1} to review

Running sputnik with:

    sputnik --conf ./frontend/gerrit.properties --changeId CHANGE_ID --revisionId COMMIT_HASH

`frontend/gerrit.properties`:
```json
connector.type=gerrit
connector.host=gerrit.pg.com
connector.port=443
connector.username=secret
connector.password=secret
connector.useHttps=true
tslint.enabled=true
tslint.script=/full/absolute/path/to/project/frontend/node_modules/tslint/bin/tslint
tslint.configurationFile=tslint.json
```

I'm **not getting any errors**, even when I change **`tslint.script` to an invalid value** like:

    tslint.script=xxxx

**Comment by SpOOnman** [comment] 2017-07-31 07:53
Please paste a log that is generated during execution. Thanks!

**Comment by SpOOnman** [comment] 2018-01-31 14:04
I think that #176 was the cause for this. Closing as #177 is now merged.

**Closed by SpOOnman** 2018-01-31 14:04 UTC
